id: AAC82F6AF
title: Aspiration for Rebirth in Sukhāvatī
type: translation
pechas:
- I061EE9EE
- I7BDCCDFD
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:06:29.970050
  last_modified_at: 2023-01-04 12:06:29.970059
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I061EE9EE/0B4D: 6BED
  I7BDCCDFD/7A46: 6BED
